/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.DB_Connection;
import javafx.scene.control.PasswordField;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Simon_
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlN = new javax.swing.JPanel();
        btnPnl = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        cnclBtn = new javax.swing.JButton();
        pnlE = new javax.swing.JPanel();
        pnlW = new javax.swing.JPanel();
        pnlC = new javax.swing.JPanel();
        usrLblPnl = new javax.swing.JPanel();
        usrLbl = new javax.swing.JLabel();
        userTxtPnl = new javax.swing.JPanel();
        usrTxt = new javax.swing.JTextField();
        psswrLblPnl = new javax.swing.JPanel();
        psswrdLbl = new javax.swing.JLabel();
        psswrdTxtPnl = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 51, 55));

        pnlN.setPreferredSize(new java.awt.Dimension(400, 75));
        getContentPane().add(pnlN, java.awt.BorderLayout.PAGE_START);

        btnPnl.setPreferredSize(new java.awt.Dimension(400, 39));

        okBtn.setText("OK");
        okBtn.setPreferredSize(new java.awt.Dimension(67, 25));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        btnPnl.add(okBtn);

        cnclBtn.setText("Cancel");
        btnPnl.add(cnclBtn);

        getContentPane().add(btnPnl, java.awt.BorderLayout.PAGE_END);

        pnlE.setPreferredSize(new java.awt.Dimension(75, 251));
        getContentPane().add(pnlE, java.awt.BorderLayout.LINE_END);

        pnlW.setPreferredSize(new java.awt.Dimension(75, 251));
        getContentPane().add(pnlW, java.awt.BorderLayout.LINE_START);

        pnlC.setPreferredSize(new java.awt.Dimension(300, 240));

        usrLblPnl.setPreferredSize(new java.awt.Dimension(80, 26));

        usrLbl.setText("Username");
        usrLblPnl.add(usrLbl);

        pnlC.add(usrLblPnl);

        userTxtPnl.setPreferredSize(new java.awt.Dimension(155, 36));

        usrTxt.setPreferredSize(new java.awt.Dimension(155, 26));
        usrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTxtActionPerformed(evt);
            }
        });
        userTxtPnl.add(usrTxt);

        pnlC.add(userTxtPnl);

        psswrLblPnl.setPreferredSize(new java.awt.Dimension(80, 26));

        psswrdLbl.setText("Password");
        psswrLblPnl.add(psswrdLbl);

        pnlC.add(psswrLblPnl);

        psswrdTxtPnl.setPreferredSize(new java.awt.Dimension(155, 36));

        passwordField.setPreferredSize(new java.awt.Dimension(155, 26));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        psswrdTxtPnl.add(passwordField);

        pnlC.add(psswrdTxtPnl);

        getContentPane().add(pnlC, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrTxtActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        String user = usrTxt.getText();
        String password = new String(passwordField.getText());
        if(DB_Connection.connect(user, password) != null){
            JOptionPane.showMessageDialog(null,"User found");
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "User not found");
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPnl;
    private javax.swing.JButton cnclBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel pnlC;
    private javax.swing.JPanel pnlE;
    private javax.swing.JPanel pnlN;
    private javax.swing.JPanel pnlW;
    private javax.swing.JPanel psswrLblPnl;
    private javax.swing.JLabel psswrdLbl;
    private javax.swing.JPanel psswrdTxtPnl;
    private javax.swing.JPanel userTxtPnl;
    private javax.swing.JLabel usrLbl;
    private javax.swing.JPanel usrLblPnl;
    private javax.swing.JTextField usrTxt;
    // End of variables declaration//GEN-END:variables
}
